version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an version of golang: 1.17, 1.18
        VARIANT: 6.0

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

# >> /usr/local/apache2/conf/httpd.conf

    volumes:
      - unix_sock:/var/run/go
    ports:
      - "8080:80"
    environment:
      - CGI=True
      - APP_SOCK_PATH=/var/run/go/go.sock
    # env_file:
    #   # Ensure that the variables in .env match the same variables in devcontainer.json
    #   - .env
    # # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # # network_mode: service:db

    # # Uncomment the next line to use a non-root user for all processes.
    # # user: node

    # # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # # (Adding the "ports" property to this file will not forward from a Codespace.)

  web:
    # image: httpd:2.4-bullseye
    image: httpd:2.4
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - $PWD/Caddyfile:/etc/caddy/Caddyfile
    #   - $PWD/site:/srv
    #   - caddy_data:/data
    #   - caddy_config:/config
    networks:
      - default
      - shared-network
    volumes:
      - unix_sock:/var/run/go
      
networks:
  # 外部から見えるネットワーク
  # Azureで作っておく()
  shared-network:
    # external: true
volumes:
  unix_sock: